"""add subjects and subject overviews

Revision ID: d4d27f5c4b8f
Revises: dac26341dd14
Create Date: 2026-06-24 17:11:19.476344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d27f5c4b8f'
down_revision: Union[str, Sequence[str], None] = 'dac26341dd14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'batch_year',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.alter_column('classes', 'batch_year',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
